Task 2
DmitriyLadutsko/IBA-react-js pull request #2
Opened 2020-10-13 08:38 UTC by DmitriyLadutsko

2020-10-13 08:41 UTC, DmitriyLadutsko commented
сори... некрасивый PR получился(

2020-10-14 07:02 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/95954578-33ffeb00-0e04-11eb-9814-dbb71db681fc.png)
карточка должна менять стили при включении и выключении чекбокса.
Если я выключу включенный чекбокс, карточка не изменится

2020-10-14 07:06 UTC, dima19972525 requested changes
поправьте изменения (постараюсь сегодня еще раз проверить)

2020-10-14 07:06 UTC, dima19972525 commented on src/Card/index.js
> +        },
мы должны хранить состояние чекбокса, чтобы от него отталкиваться в дальнейшем (при включении, выключении чекбокса не только backgroundColor может меняться)
Лучше изменить на это:
```js
const [isCheked, setChecked] = useState(false);
```
и т.д.

2020-10-14 08:07 UTC, DmitriyLadutsko commented on src/Card/index.js
> +        },
возможно, поспешил хуками пользоваться (class-based - наверное, было бы проще...)

2020-10-14 08:27 UTC, dima19972525 approved these changes
поправьте изменения и мерж

2020-10-14 08:27 UTC, dima19972525 commented on src/Card/index.js
> +                <input type="checkbox" onClick={() => setChecked(!isChecked)}/>
Можно привязать значения state к инпуту.
```js
 <input
                    type="checkbox"
                    checked={isChecked}
                    onClick={() => setChecked(!isChecked)}
                />
```

2020-10-14 08:27 UTC, dima19972525 commented on src/Card/index.js
> +        <div className="Card" style={changeStyleCard()}>
измените на это:
```js
            style={{ backgroundColor: isChecked ? '#ebc2f5' : '#c2f5f5' }}>
```
и удалите функцию changeStyleCard.
(в будующем всеравно никаких имзенений с карточками не будет, кроме этого background, эта функция не нужна. Также её название смахивает на изменение какого-либо свойства `changeStyleCard`, я бы переименовал на `getStyleCard`.

2020-10-14 08:46 UTC, merged