Task 4
DmitriyLadutsko/IBA-react-js pull request #4
Opened 2020-10-15 23:03 UTC by DmitriyLadutsko

2020-10-16 07:07 UTC, dima19972525 commented
нажимаю на редактирование карточки
![image](https://user-images.githubusercontent.com/23092460/96223878-5118f300-0f97-11eb-8306-329423c268b2.png)
Сохраняю, получаю пустой текст
![image](https://user-images.githubusercontent.com/23092460/96223898-59712e00-0f97-11eb-9ab4-f8215dc976e4.png)

2020-10-16 07:20 UTC, dima19972525 requested changes
Поправьте изменения

2020-10-16 07:20 UTC, dima19972525 commented on src/App.js
> +        const listCards = this.state.cards.slice().map((card, index) =>
нет смысла использовать slice, map и так возвращает новый массив (конечно, если вы не меняете значения пропсов прямо в компоненьте Card, если да, то так недолжно быть)

2020-10-16 07:20 UTC, dima19972525 commented on src/App.js
> +                key={index.toString()}
можно и без toString, просто index

2020-10-16 07:20 UTC, dima19972525 commented on src/Card/index.js
> +    }
переместите этот if после всех объявлений констант стейта

2020-10-16 07:20 UTC, dima19972525 commented on src/Card/index.js
>                  <textarea
в хеадере можно оставить просто input, хеадеру ненужны несколько строк (необязательно)

2020-10-16 07:39 UTC, DmitriyLadutsko commented
С пустым текстом после редактирования что-то пока не соображу.. Если внести изменения, пусть даже пробелы, тогда всё сохраняется - записывается в переменные changedCaption и changedText. Но как defaultValue сразу присвоить этим переменным..?(

2020-10-19 07:03 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/96411878-dd265700-11f1-11eb-920b-678dbabcbd60.png)
Изменяю карточку -> пишу что-нибдуь в хеадере -> отменяю изменения (нажимаю на крестик) -> вижу дефолтный заголовок карточки (так и должно быть) -> нажимаю на кнопку "изменить карточку" -> вижу изменения, которые я вводил раньше.

Когда я нажимаю на изменение карточки, текст в инпутах должен быть точно такимже, как сейчас показывается пользователю.
Поправьте это.

2020-10-19 07:06 UTC, dima19972525 commented
Вы можете изменять массив в компоненьте App.js (я имею в виду массив карточек) только тогда, когда пользователь нажимает на кнопку "сохранить изменения".

Поумолчанию, вы показываете пользователю значения пропсов, что вы передаете компоненту.
В режиме редактирования у вас должен быть стейт, который при нажатии на конпку "редактировать", присваивает значения пропсов карточки. Этот стейт можете редактировать как угодно, если пользователь сохраняет изменния, просто передайте значения этого стейта в хендрел, который обновит массив в App.js

2020-10-19 07:07 UTC, dima19972525 requested changes
Поправьте баг с редактированием карточек

2020-10-20 09:40 UTC, dima19972525 commented
пока не могу проверить, проблемы с рабочим компом, с самого утра нет доступа.
(посмотрю, как появится доступ)

2020-10-20 09:46 UTC, DmitriyLadutsko commented
ок, 
я там всё поправил, должно уже быть красиво..)

2020-10-20 15:08 UTC, dima19972525 approved these changes
мерж (сор, что так поздно)

2020-10-20 15:08 UTC, dima19972525 commented on src/App.js
> +            />)
можно сделать так:
```js
                changedCaption={this.cardChangedHandler(card.id)}
```
```js
 cardChangedHandler = id => (caption, text) => {

        const cardIndex = this.state.cards.findIndex(card => {
            return card.id === id;
        });....
```

2020-10-20 15:42 UTC, merged