Task 9
DmitriyLadutsko/IBA-react-js pull request #9
Opened 2020-10-26 22:39 UTC by DmitriyLadutsko

2020-10-27 08:54 UTC, dima19972525 commented
![image](https://user-images.githubusercontent.com/23092460/97278759-33774380-184b-11eb-835e-216fab7912b1.png)
поправьте это

2020-10-27 09:17 UTC, dima19972525 requested changes
перепишите context по примеру, что я вам скинул

2020-10-27 09:17 UTC, dima19972525 commented on src/context/cardsContext.js
> +export default cardsContext;
Можно также сделать так (пример):
```js
import React, { Component } from 'react';

const { Provider, Consumer } = React.createContext();

class CardContextProvider extends Component {
  state = {
    cards: [
      {id:'id1', headerText: 'Tab number One', bodyText: 'I expect some text here...'},
      {id:'id2', headerText: 'Tab number Two', bodyText: 'I expect some text here...'},
      {id:'id3', headerText: 'Tab number Three', bodyText: 'I expect some text here...'},
      {id:'id4', headerText: 'Tab number Four', bodyText: 'I expect some text here...'},
      {id:'id5', headerText: 'Tab number Five', bodyText: 'I expect some text here...'},
      {id:'id6', headerText: 'Tab number Six', bodyText: 'I expect some text here...'},
      {id:'id7', headerText: 'Tab number Seven', bodyText: 'I expect some text here...'}
    ],
    onlyView: false
  };

  cardsToRemove = [];

  checkBoxAppHandler = () => {
    this.setState({onlyView: !this.state.onlyView});
  };

  addCardHandler = () => {    
    let cards = [...this.state.cards];
    let lastCard = cards[cards.length-1];
    let newCard = {id: 'id' + (+lastCard.id.slice(2) + 1), headerText: 'This is new Card', bodyText: 'I expect some text here...'};
    cards.push(newCard);    
    this.setState({cards: cards});
  };

  cardsToRemoveHandler = (id, state) => {
    if(state) {
      this.cardsToRemove.push(id);
    } else {
      this.cardsToRemove = this.cardsToRemove.filter(val => val!==id);
    }
  };
  
  removeCardHandler = () => {
    let cards = [...this.state.cards];    
    cards = cards.filter(val => !this.cardsToRemove.includes(val.id));
    this.setState({cards: cards});
  };

  render() {
    return (
      <Provider
        value={{
          onlyView: this.state.onlyView,
          cards: this.state.cards,
          cardsCount: this.state.cards.length,
          onAdd: this.addCardHandler,
          onRemove: this.removeCardHandler,
          removeCard: this.cardsToRemoveHandler,
          onChange: this.checkBoxAppHandler
        }} >
        {this.props.children}
      </Provider>
    );
  }
}

export { CardContextProvider, Consumer as CardContextConsumer };
```

index.js

```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './containers/App';
import './index.css';
import {CardContextProvider} from './context/Context';

ReactDOM.render(
  <CardContextProvider>
    <App />
  </CardContextProvider>,
  document.getElementById('root')
);
```
и подключаем Consumer где он нужен

2020-10-27 09:17 UTC, dima19972525 commented on src/context/cardsContext.js
> +export default cardsContext;
Способ, что я описал выше, лучше, чем тот, что используется сейчас. Т.к. провайдер намертво привязан к стейту компонента App.js, что заставляет перерендеривать полностью компонент App.js по каждому чиху (добавьте console.log в метод render и посмотрите, он выводится каждый раз, когда я банально кликаю на чекбокс карточки, т.е. при нажатие на чекбокс у меня перерендеривается все приложение)

2020-10-27 09:49 UTC, DmitriyLadutsko commented on src/context/cardsContext.js
> +export default cardsContext;
да, действительно, всё приложение (App.js) постоянно перерендеривается... спасибо, буду поправлять

2020-10-28 07:13 UTC, dima19972525 approved these changes
мерж

2020-10-28 07:30 UTC, merged